# Data paths
data:
  connections: data/raw/connections_princeton.csv
  neurons: data/raw/neurons.csv

# Single neuron analysis
single_query:
  neuron_id: DNp03
  neuron_name: null

#Multi-neuron analysis
multi_query:
  neuron_names:
    - DNa15
    - DNa03
    - DNa05
    - DNb01

# Analysis parameters
analysis:
  min_synapses: 10
  top_n_similar: 20
  similarity_threshold: 0.0
  normalization: none
  max_comparison_neurons: 200

# Output settings
output:
  use_timestamps: false
  save_raw_data: true
  use_names: true